server {
    listen 80;
    server_name _;
    root /var/www/application/public;
    absolute_redirect off;

    location = / {
        return 302 /cabinet/;
    }

    location = /cabinet {
        return 301 /cabinet/;
    }

    location = /cabinet/ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/application/public/index.php;
        fastcgi_param SCRIPT_NAME /cabinet/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/application/public;
    }

    location /cabinet/ {
        rewrite ^/cabinet/(.*)$ /$1 break;
        try_files $uri @cabinet;
    }

    location = /cabinet/index.php {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/application/public/index.php;
        fastcgi_param SCRIPT_NAME /cabinet/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/application/public;
    }

    location @cabinet {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/application/public/index.php;
        fastcgi_param SCRIPT_NAME /cabinet/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/application/public;
    }

    location ~ \.php$ {
        return 404;
    }
}
